// StarkShield v1.5 -- proof_verifiers
//
// Routes ZK proof verification to the appropriate Garaga-generated verifier contract.
// Each circuit type (range_proof, balance_sufficiency, etc.) has its own verifier contract
// generated by the Garaga CLI from the circuit's verification key.

#[starknet::contract]
pub mod ProofVerifier {
    use starknet::ContractAddress;
    use starknet::storage::{
        Map, StoragePathEntry, StoragePointerReadAccess, StoragePointerWriteAccess,
    };
    use core::num::traits::Zero;
    use crate::interfaces::IProofVerifier;

    #[storage]
    struct Storage {
        owner: ContractAddress,
        verifier_addresses: Map<u8, ContractAddress>,
    }

    #[event]
    #[derive(Drop, starknet::Event)]
    enum Event {
        VerifierUpdated: VerifierUpdated,
    }

    #[derive(Drop, starknet::Event)]
    struct VerifierUpdated {
        #[key]
        circuit_type: u8,
        verifier_address: ContractAddress,
    }

    #[constructor]
    fn constructor(ref self: ContractState, owner: ContractAddress) {
        self.owner.write(owner);
    }

    #[abi(embed_v0)]
    impl ProofVerifierImpl of IProofVerifier<ContractState> {
        fn verify(
            self: @ContractState,
            circuit_type: u8,
            public_inputs: Span<felt252>,
            proof: Span<felt252>,
        ) -> bool {
            let verifier_addr = self.verifier_addresses.entry(circuit_type).read();
            if verifier_addr.is_zero() {
                return false;
            }
            // TODO: Dispatch to the Garaga-generated verifier contract.
            // In production, this calls the circuit-specific verifier:
            //   IGaragaVerifierDispatcher { contract_address: verifier_addr }
            //       .verify_ultra_keccak_zk_honk_proof(proof, public_inputs)
            //
            // For now, having a non-zero verifier address means verification passes.
            // This will be replaced once Garaga verifier contracts are generated.
            true
        }

        fn set_verifier(
            ref self: ContractState,
            circuit_type: u8,
            verifier_address: ContractAddress,
        ) {
            let caller = starknet::get_caller_address();
            assert(caller == self.owner.read(), 'only owner');
            self.verifier_addresses.entry(circuit_type).write(verifier_address);
            self.emit(VerifierUpdated { circuit_type, verifier_address });
        }
    }
}
